name: Deploy to Kubernetes

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t your-dockerhub-username/image-name:latest .

      - name: Configure Kubernetes
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ~/.kube/config
          kubectl cluster-info

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSERNAME }}  # Add this secret if needed
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: Push Docker Image
        run: docker push your-dockerhub-username/image-name:latest

      - name: Deploy to Cluster
        run: kubectl apply -f deployment.yaml
